#!/usr/bin/env python3.5

from sys import exit, argv
from json import load
from subprocess import run
from hashlib import sha1

class BuildUnit:

    def __init__(self, build_filename):
        self.__parse_buildfile(build_filename)
        
    def __parse_buildfile(self, build_filename):
        with open(build_filename) as f:
            self.buildfile = load(f)
    
    def Build(self):
        for filename in self.buildfile['files']:
            run('gcc -c {0} -o {1}'.format(filename, sha1(filename).hexdigest()))

def main(argv):
    unit = BuildUnit('./Buildfile')
    unit.Build()

if __name__ == "__main__":
    exit(main(argv))
